// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
// @eslint-disable camelcase

import { MobilettoOrmSyncError } from "mobiletto-orm-typedef";

export default defineEventHandler(async (event) => {
  filterErrors(event, "destination.delete", async (event) => {
    requireAdminAccountObject(event, "destination.delete", async (event, _session, _account) => {
      const id = event.context.params.id;
      const destinationRepo = destinationRepository();
      try {
        const destination_by_id = await destinationRepo.safeFindById(id);
        if (destination_by_id) {
          return await destinationRepo.remove(destination_by_id);
        }
      } catch (e) {
        if (e instanceof MobilettoOrmSyncError) {
          logger.warn(`destination.delete: sync error: ${e}`);
          throw conflict();
        }
        logger.error(`destination.delete: unexpected error: ${e}`);
        throw serverError();
      }
      throw notFound(id);
    });
  });
});
