/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { MobilettoOrmNotFoundError, MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { DestinationType, DestinationTypeDef } from "yuebing-model";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "destination.update", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "destination.update", async (event: H3Event, session, account) => {
      const destinationRepo = destinationRepository();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(destinationRepo.typeDef.idFieldName());
      const obj: DestinationType = await readBody(event);
      if (!obj) {
        throw badRequest();
      }
      if (DestinationTypeDef.id(obj) !== id) {
        const errs: MobilettoOrmValidationErrors = {};
        errs[destinationRepo.typeDef.idFieldName()] = ["mismatch"];
        throw validationError(errs);
      } else {

        return await destinationRepo.update(obj);
      }
    });
  });
});
