// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
// @eslint-disable camelcase

export default defineEventHandler(async (event) => {
  filterErrors(event, "destination.lookup", async (event) => {
    requireAdminAccountObject(event, "destination.lookup", async (event, _session, _account) => {
      const id = event.context.params.id;
      const destinationRepo = destinationRepository();
      const destination_by_id = await destinationRepo.safeFindById(id);
      if (destination_by_id) return destination_by_id;
      throw createError({ statusCode: 404, statusMessage: "not found" });
    });
  });
});
