/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event, H3Error } from "h3";
import { MobilettoOrmSyncError } from "mobiletto-orm-typedef";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "destination.delete", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "destination.delete", async (event: H3Event, session, account) => {
      const destinationRepo = destinationRepository();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(destinationRepo.typeDef.idFieldName());
      try {
        const destination_by_id = await destinationRepo.safeFindById(id);
        if (destination_by_id) {

          return await destinationRepo.remove(destination_by_id);
        }
      } catch (e) {
        if (e instanceof H3Error) throw e;
        if (e instanceof MobilettoOrmSyncError) {
          logger.warn(`destination.delete: sync error: ${e}`);
          throw conflict();
        }
        logger.error(`destination.delete: unexpected error: ${e}`);
        throw serverError();
      }
      throw notFound(id);
    });
  });
});
