<!-- DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen -->

<template>
  <v-container>
    <v-row v-if="successSnackbar && successSnackbar.length > 0">
      <KitSnackbarSuccess :text="successSnackbar" />
    </v-row>
    <v-row v-else-if="errorSnackbar && errorSnackbar.length > 0">
      <KitSnackbarError :text="errorSnackbar" />
    </v-row>
    <v-row>
      <v-col>
        <h2>{{ adminTitle() }}</h2>
        <b v-if="messageExists('admin_title_mediaProfile_administration_details', messages)">
          {{ messages.admin_title_mediaProfile_administration_details }}
        </b>
      </v-col>
    </v-row>
    <v-row v-if="addingObject">
      <v-col>
        <OrmForm
          v-if="allRefsLoaded() && mediaProfileTypeDef"
          form-name="add_mediaProfile_form"
          :type-def="mediaProfileTypeDef"
          :type-name-message="typeNameMessage"
          :thing="addObject"
          :fields="mediaProfileTypeDefFields"
          :create="true"
          :read-only-object="() => false"
          :server-errors="createMediaProfileServerErrors"
          :label-prefixes="labelPfx"
          :hint-suffixes="['_description']"
          @submitted="onAddSubmitted"
          @update="onAddUpdated"
          @cancel="onAddCancel"
        />
      </v-col>
    </v-row>
    <v-row v-else-if="Object.keys(editingObject).length > 0">
      <v-col>
        <OrmForm
          v-if="allRefsLoaded() && mediaProfileTypeDef"
          form-name="edit_mediaProfile_form"
          :type-def="mediaProfileTypeDef"
          type-name-message="typeNameMessage"
          :thing="editingObject"
          :fields="mediaProfileTypeDefFields"
          :create="false"
          :read-only-object="() => false"
          :server-errors="editMediaProfileServerErrors"
          :label-prefixes="labelPfx"
          :hint-suffixes="['_description']"
          @submitted="onEditSubmitted"
          @update="onEditUpdated"
          @cancel="onEditCancel"
        />
      </v-col>
    </v-row>
    <v-row v-else-if="allRefsLoaded() && mediaProfileTypeDef">
      <v-col>
        <v-container>
          <v-form @submit.prevent="searchObjects">
            <v-row v-if="(mediaProfileList && mediaProfileList.length > 0) || searched">
              <v-col>
                  <v-text-field
                    v-model="searchTerms"
                    :label="messages.label_search"
                    :disabled="mediaProfileStore.mediaProfileBusy"
                    type="text"
                    name="searchTerms"
                    class="form-control"
                    @keyup.enter="searchObjects"
                  />
              </v-col>
            </v-row>
            <v-row>
              <v-col v-if="singleRefSearchField">
                  {{ refSearchFields[0].title }}
              </v-col>
              <v-col v-else>
                <v-select
                  v-model="selectedRef"
                  :v-bind="selectedRef"
                  :items="refSearchFields"
                  :full-width="false"
                  name="selectedRef"
                  class="form-control"
                />
              </v-col>
              <v-col v-show="selectedRef === 'media'">
                  <v-select
                      v-model="searchRef.media"
                      :v-bind="searchRef.media"
                      :label="fieldMessages.media"
                      :items="refMedia.items"
                      item-value="value"
                      item-title="label"
                      :full-width="false"
                      name="searchRef_media"
                      class="form-control"
                      @update:model-value="searchObjects"
                  />
              </v-col>
            </v-row>
            <v-row>
              <v-col>
                <v-btn class="btn btn-primary" :disabled="mediaProfileStore.mediaProfileBusy" @click.stop="searchObjects">
                  <Icon name="material-symbols:search" />
                </v-btn>
              </v-col>
            </v-row>
          </v-form>
          <v-row>
            <v-col>
              <table v-if="mediaProfileList && mediaProfileList.length > 0">
                <thead>
                <tr>
                  <th v-for="(tableField, tableFieldIndex) in tableFields" :key="tableFieldIndex">
                  {{ fieldMessages[tableField] }}
                  </th>
                  <th v-if="Object.keys(actionConfigs).length > 0">
                  <Icon name="material-symbols:target" />
                  </th>
                  <th></th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="(obj, objIndex) in mediaProfileList" :key="objIndex">
                  <td v-for="(fieldName, fieldIndex) in tableFields" :key="fieldIndex">
                  <OrmFieldDisplay v-if="mediaProfileTypeDef.fields[fieldName] || fieldName.startsWith('_meta')" :field="fieldName.startsWith('_meta') ? metaField(fieldName) : mediaProfileTypeDef.fields[fieldName]" :value="deepGet(obj, fieldName)" />
                  </td>
                  <td v-if="Object.keys(actionConfigs).length > 0">
                  <div v-for="(action, actionIndex) in Object.keys(actionConfigs)" :key="actionIndex">
                  <NuxtLink
                    v-if="actionEnabled(obj, action)"
                    :to="{ path: `${actionConfig(action).path}/${deepGet(obj, mediaProfileTypeDef.idField(obj) as string)}` }"
                    >
                      <v-btn>
                          {{ messages[actionConfig(action).message] }}
                        </v-btn>
                      </NuxtLink>
                    </div>
                  </td>
                  <td>
                    <v-btn v-if="canEdit(obj, mediaProfileList)" :disabled="mediaProfileStore.mediaProfileBusy" @click.stop="showEditOrm(obj)">
                      <Icon name="material-symbols:edit" />
                    </v-btn>
                  </td>
                  <td>
                    <v-btn v-if="canDelete(obj, mediaProfileList)" :disabled="mediaProfileStore.mediaProfileBusy" @click.stop="delObject(obj)">
                      <Icon name="material-symbols:delete" />
                    </v-btn>
                  </td>
                </tr>
                </tbody>
              </table>
            </v-col>
          </v-row>
          <v-row v-if="canAdd()">
            <v-col>
              <v-btn class="btn btn-primary" :disabled="mediaProfileStore.mediaProfileBusy" @click.stop="showAddOrm">
                <Icon name="material-symbols:add" />
              </v-btn>
            </v-col>
          </v-row>
        </v-container>
      </v-col>
    </v-row>
    <v-row v-else>
      <v-col>
        <Icon name="material-symbols:clock-outline" />
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
  import { ref, watch, Ref } from "vue";
  import { storeToRefs } from "pinia";
  import {
    MobilettoOrmFieldDefConfig,
    MobilettoOrmObject,
    MobilettoOrmTypeDef,
    MobilettoOrmValidationErrors,
    metaField
  } from "mobiletto-orm-typedef";
  import { MediaProfileType, MediaProfileTypeDef } from "yuebing-model";
  import { findMessage, messageExists, parseMessage, normalizeMsg } from "hokey-runtime";
  import { useSessionStore } from "~/stores/sessionStore";
  import { useMediaProfileStore } from "~/stores/model/mediaProfileStore";
  import { useMediaStore } from "~/stores/model/mediaStore";
  import { deepUpdate } from "~/utils/model/adminHelper";
  import { MobilettoOrmFindApiOpts } from "~/utils/model/storeHelper";
  const successSnackbar = ref("");
  const errorSnackbar = ref("");
  type ActionConfig = {
    path: string;
    message: string;
    when: (obj: MobilettoOrmObject) => boolean;
  };
  const props = withDefaults(
    defineProps<{
      labelPrefixes: string[];
      typeNameMessage: string;
      msgAddSuccess: string;
      msgAddError: string;
      msgEditSuccess: string;
      msgEditError: string;
      msgDeleteSuccess: string;
      msgDeleteError: string;
      actionConfigs: Record<string, ActionConfig>;
      canAdd: () => boolean;
      canEdit: (obj: MobilettoOrmObject, objList: MobilettoOrmObject[]) => boolean;
      canDelete: (obj: MobilettoOrmObject, objList: MobilettoOrmObject[]) => boolean;
      deleteConfirmationMessage: string;
      maxDeleteConfirmations: number;
    }>(),{
      labelPrefixes: () => ["label_", ""],
      typeNameMessage: () => "typename_mediaProfile",
      msgAddSuccess: () => "admin_info_added",
      msgAddError: () => "admin_info_add_error",
      msgEditSuccess: () => "admin_info_edited",
      msgEditError: () => "admin_info_edit_error",
      msgDeleteSuccess: () => "admin_info_deleted",
      msgDeleteError: () => "admin_info_delete_error",
      actionConfigs: () => ({}),
      canAdd: () => true,
      canEdit: () => true,
      canDelete: () => true,
      maxDeleteConfirmations: () => 3,
    },
  );

  const emit = defineEmits<{
    added: [obj: MobilettoOrmObject];
    addCanceled: [];
    edited: [obj: MobilettoOrmObject];
    editCanceled: [obj: MobilettoOrmObject];
    deleted: [obj: MobilettoOrmObject];
  }>();

  const labelPfx: Ref<string[]> = ref(["admin_label_mediaProfile_", "label_", ""]);
  if (props.labelPrefixes) {
    props.labelPrefixes.forEach((p: string) => {
      if (!labelPfx.value.includes(p)) labelPfx.value.unshift(p);
    });
  }

  const sessionStore = useSessionStore();
  const { localeMessages } = storeToRefs(sessionStore);
  const messages = localeMessages;

  const adminTitle = () => messageExists("admin_title_mediaProfile_administration", messages.value)
    ? messages.value.admin_title_mediaProfile_administration
    : parseMessage("admin_title_site_administration", messages.value, { title: findMessage(props.typeNameMessage, messages.value, [""])});

  const addingObject = ref(false);
  const addObject = ref({} as MediaProfileType);
  const createMediaProfileServerErrors = ref({} as MobilettoOrmValidationErrors);

  const editingObject = ref({} as MediaProfileType);
  const editMediaProfileServerErrors = ref({} as MobilettoOrmValidationErrors);
  const deleteMediaProfileServerErrors = ref({} as MobilettoOrmValidationErrors);

  const pageNumber = ref(1);
  const pageSize = ref(20);
  const searchTerms = ref("");
  const searched = ref(false);
  const lastQuery = ref({});

  const tableFields: Ref<string[]> = ref([]);

  const fieldMessages: Ref<Record<string, string>> = ref({});
  const initFieldMessages = (tableFields: string[]) => {
      const defaultFieldMessages: Record<string, string> = {};
      tableFields.forEach((f: string) => {
        defaultFieldMessages[f] = findMessage(normalizeMsg(f), messages.value, props.labelPrefixes);
      });      fieldMessages.value = defaultFieldMessages;
  };

  const mediaProfileStore = useMediaProfileStore();
  const { mediaProfileList  } = storeToRefs(mediaProfileStore);
  const mediaProfileTypeDef: Ref<MobilettoOrmTypeDef | null> = ref(null);
  const mediaProfileTypeDefFields: Ref<MobilettoOrmFieldDefConfig[] | undefined> = ref(undefined);
  const searchQuery = () => {
      const q: MobilettoOrmFindApiOpts = {};
      if (searchTerms.value && searchTerms.value.trim().length > 0) q.textSearch = searchTerms.value;
      const val = searchRef.value[selectedRef.value as string];
      if (val && val.length > 0) {
        q.field = selectedRef.value;
        q.value = val;
      }
      return Object.keys(q).length > 0 ? q : undefined;
  };

  const searchObjects = () => {
    const query = searchQuery();
    if (!query) return; // something was wrong, don't send the query
    if (lastQuery.value && JSON.stringify(lastQuery.value) === JSON.stringify(query)) {
      // not sending duplicate search
    } else {
      searched.value = true;
      lastQuery.value = Object.assign({}, query);
      mediaProfileStore.search(query);
    }
  };

  const navigating = ref(false);
  const initTypeDef = () => {
    const typeDef = MediaProfileTypeDef.extend({
      fields: {
      
        media: { ...refMedia.value },
      
        from: { ...refMediaProfile.value },
      
        subProfiles: { ...refMediaProfile.value },
      
      }
    });
    mediaProfileTypeDefFields.value = typeDef.tabIndexedFields();
    mediaProfileTypeDef.value = typeDef;
    tableFields.value = mediaProfileTypeDef.value.tableFields && Array.isArray(mediaProfileTypeDef.value.tableFields)
      ? mediaProfileTypeDef.value.tableFields
      : mediaProfileTypeDef.value.primary
        ? [mediaProfileTypeDef.value.primary, "ctime", "mtime"]
        : ["id", "ctime", "mtime"];
    initFieldMessages(tableFields.value);
  }

  const allRefs: Ref<Boolean>[] = [];
  const allRefsLoaded = () => allRefs.length === 2 && allRefs.filter(r => r.value === true).length === 2;
  const refSearchFields = ref([] as { value: string, title: string }[]);
  const selectedRef = ref("media");
  const searchRef: Ref<Record<string, string>> = ref({});
  searchRef.value.media = "";
  refSearchFields.value.push({ value: "media", title: findMessage("media", messages.value, ["typename_", ...props.labelPrefixes]) });
  const singleRefSearchField = ref(refSearchFields.value.length === 1);
  const refMedia = ref({} as MobilettoOrmFieldDefConfig);
  const refMediaLoaded = ref(false);
  allRefs.push(refMediaLoaded);
  const mediaStore = useMediaStore();
  const { mediaList } = storeToRefs(mediaStore);

  watch(mediaList, (newList) => {
    if (newList && newList.length === 0) {
      if (navigating.value) return;
      navigating.value = true;
      navigateTo("/admin/media/setup");
    } else if (newList && newList.length > 0) {
      refMedia.value.values = newList.map((s) => s.name);
      refMedia.value.labels = newList.map((s) => s.name);
      refMedia.value.items = newList.map((s) => ({
        label: s.name,
        value: s.name,
        title: s.name,
        rawLabel: true,
      }));
      MediaProfileTypeDef.fields.media.items = refMedia.value.items;
      refMediaLoaded.value = true;
      if (allRefsLoaded()) {
        initTypeDef();
      }
    }
  });const refMediaProfile = ref({} as MobilettoOrmFieldDefConfig);
  const refMediaProfileLoaded = ref(false);
  allRefs.push(refMediaProfileLoaded);

  watch(mediaProfileList, (newList) => {
    if (newList && newList.length === 0) {
      if (navigating.value) return;
      navigating.value = true;
      navigateTo("/admin/mediaProfile/setup");
    } else if (newList && newList.length > 0) {
      refMediaProfile.value.values = newList.map((s) => s.name);
      refMediaProfile.value.labels = newList.map((s) => s.name);
      refMediaProfile.value.items = newList.map((s) => ({
        label: s.name,
        value: s.name,
        title: s.name,
        rawLabel: true,
      }));
      MediaProfileTypeDef.fields.from.items = refMediaProfile.value.items;
      MediaProfileTypeDef.fields.subProfiles.items = refMediaProfile.value.items;
      refMediaProfileLoaded.value = true;
      if (allRefsLoaded()) {
        initTypeDef();
      }
    }
  });
  const onAddUpdated = (update: { field: string; value: any }) => {
    deepUpdate(addObject.value, update.field, update.value);
  };
  const onAddSubmitted = async (obj: MobilettoOrmObject) => {
    await mediaProfileStore
      .create(obj as MediaProfileType, createMediaProfileServerErrors);
    addingObject.value = false;
    successSnackbar.value = parseMessage(props.msgAddSuccess, messages.value, {
        type: messages.value.typename_mediaProfile,
        id: MediaProfileTypeDef.id(obj),
    });
    emit("added", obj);
    addObject.value = {} as MediaProfileType;
    return await mediaProfileStore.search();
  }
  watch(createMediaProfileServerErrors, () => {
    if (createMediaProfileServerErrors.value && Object.keys(createMediaProfileServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgAddError, messages.value, {
        type: messages.value.typename_mediaProfile,
        error: JSON.stringify(createMediaProfileServerErrors),
      });
    }
  });

  const showAddOrm = () => {
    addingObject.value = true;
  };
  const onAddCancel = () => {
    addingObject.value = false;
    emit("addCanceled");
  };

  const onEditUpdated = (update: { field: string; value: any }) => {
    if (editingObject.value) {
      deepUpdate(editingObject.value, update.field, update.value);
    }
  };

  const onEditSubmitted = async (obj: MobilettoOrmObject) => {
    await mediaProfileStore
      .update(obj as MediaProfileType, editMediaProfileServerErrors);
    editingObject.value = {} as MediaProfileType;
    successSnackbar.value = parseMessage(props.msgEditSuccess, messages.value, {
      type: messages.value.typename_mediaProfile,
      id: MediaProfileTypeDef.id(obj),
    });
    emit("edited", obj);
    return await mediaProfileStore.search();
  };
  watch(editMediaProfileServerErrors, () => {
    if (editMediaProfileServerErrors.value && Object.keys(editMediaProfileServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgEditError, messages.value, {
        type: messages.value.typename_mediaProfile,
        id: MediaProfileTypeDef.id(editingObject.value),
        error: JSON.stringify(editMediaProfileServerErrors),
      });
    }
  });

  const showEditOrm = (obj: MobilettoOrmObject) => {
    if (Object.keys(editingObject.value).length > 0) {
      // already editing something else
      return;
    }
    if (obj) {
      const id = MediaProfileTypeDef.id(obj);
      if (id && id.length > 0) {
        addingObject.value = false; // ensure add form is closed
        editingObject.value = JSON.parse(JSON.stringify(obj)) as MediaProfileType;
      }
    }
  };
  const onEditCancel = () => {
    emit("editCanceled", editingObject.value);
    editingObject.value = {} as MediaProfileType;
  };

  const actionConfig = (action: string) => {
    return props.actionConfigs[action];
  };

  const actionEnabled = (obj: MobilettoOrmObject, action: string) => {
    const cfg = props.actionConfigs[action];
    if (!cfg.when || typeof cfg.when !== "function") {
      return true;
    }
    if (typeof cfg.when === "function") {
      return cfg.when(obj) === true;
    }
    return true;
  };
  const delConfirmCount = ref(0);
  const deletingObject: Ref<MobilettoOrmObject | null> = ref(null);
  const delObject = (obj: MobilettoOrmObject) => {
      if (props.deleteConfirmationMessage && props.deleteConfirmationMessage.length > 0 && delConfirmCount.value < props.maxDeleteConfirmations) {
          const confirmationMessage = parseMessage(props.deleteConfirmationMessage, messages.value, {
              id: MediaProfileTypeDef.id(obj)
          });
          if (confirm(confirmationMessage)) {
              delConfirmCount.value = delConfirmCount.value + 1;
          } else {
              delConfirmCount.value = 0;
              return;
          }
      }
      deletingObject.value = obj;
      const id = MediaProfileTypeDef.id(obj);
      mediaProfileStore.delete(id, deleteMediaProfileServerErrors)
          .then(() => {
              successSnackbar.value = parseMessage(props.msgDeleteSuccess, messages.value, {
                  type: messages.value.typename_mediaProfile,
                  id: MediaProfileTypeDef.id(obj),
              });
              emit("deleted", obj);
              return mediaProfileStore.search();
          });
  };
  watch(deleteMediaProfileServerErrors, () => {
    if (deleteMediaProfileServerErrors.value && Object.keys(deleteMediaProfileServerErrors.value).length > 0) {
        errorSnackbar.value = parseMessage(props.msgDeleteError, messages.value, {
            type: messages.value.typename_mediaProfile,
            id: deletingObject.value ? MediaProfileTypeDef.id(deletingObject.value) : "null",
            error: JSON.stringify(deleteMediaProfileServerErrors),
        });
    }
  });
  watch(mediaProfileList, (newList) => {
    if (newList && Array.isArray(newList) && newList.length === 0 && searchTerms.value && searchTerms.value.length === 0) {
      if (navigating.value) return;
      navigating.value = true;
      navigateTo("/admin/mediaProfile/setup");
    }
  });

  const initRefs = async () => {
    const refSearches: Promise<MobilettoOrmObject[]>[] = [];
    refSearches.push(mediaStore.search());
    await Promise.all(refSearches);
    
  };
  mediaProfileStore.search().then(() => {
    initRefs();
  });
</script>
