/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { MediaType, MediaTypeDef } from "yuebing-model";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "media.create", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "media.create", async (event: H3Event, session, account) => {
      const mediaRepo = mediaRepository();
      if (mediaRepo.initialize) await mediaRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(mediaRepo.typeDef.idFieldName());
      const obj: MediaType = await readBody(event);
      if (!obj) {
        throw badRequest();
      }
      if (MediaTypeDef.id(obj) !== id) {
        const errs: MobilettoOrmValidationErrors = {};
        errs[mediaRepo.typeDef.idFieldName()] = ["mismatch"];
        throw validationError(errs);
      } else {
        return await mediaRepo.create(obj);
      }
    });
  });
});
