/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "media.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "media.lookup", async (event: H3Event, session, account) => {
      const mediaRepo = mediaRepository();
      const id =event?.context?.params?.id;
      if (!id) throw notFound(mediaRepo.typeDef.idFieldName());
      const media_by_id = await mediaRepo.safeFindById(id);
      if (media_by_id) return media_by_id;
      throw notFound(id);
    });
  });
});
