/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "mediaProperty.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "mediaProperty.lookup", async (event: H3Event, session, account) => {
      const mediaPropertyRepo = mediaPropertyRepository();
      const id =event?.context?.params?.id;
      if (!id) throw notFound(mediaPropertyRepo.typeDef.idFieldName());
      const mediaProperty_by_id = await mediaPropertyRepo.safeFindById(id);
      if (mediaProperty_by_id) return mediaProperty_by_id;
      throw notFound(id);
    });
  });
});
