/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { MobilettoOrmNotFoundError, MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { MediaPropertyType, MediaPropertyTypeDef } from "yuebing-model";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "mediaProperty.update", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "mediaProperty.update", async (event: H3Event, session, account) => {
      const mediaPropertyRepo = mediaPropertyRepository();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(mediaPropertyRepo.typeDef.idFieldName());
      const obj: MediaPropertyType = await readBody(event);
      if (!obj) {
        throw badRequest();
      }
      if (MediaPropertyTypeDef.id(obj) !== id) {
        const errs: MobilettoOrmValidationErrors = {};
        errs[mediaPropertyRepo.typeDef.idFieldName()] = ["mismatch"];
        throw validationError(errs);
      } else {

        return await mediaPropertyRepo.update(obj);
      }
    });
  });
});
