// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { AccountType, AccountTypeDef } from "yuebing-model";
import * as a from "~/utils/services/serviceUtil";
import { MobilettoOrmObject, MobilettoOrmPurgeResults } from "mobiletto-orm";

export const accountService = {
  searchAccount,
  findAccount,
  updateAccount,
  deleteAccount,
};

function searchAccount(query?: MobilettoOrmFindApiOpts): Promise<AccountType[]> {
  return $fetch("/api/model/account", a.authPostJson(query)).then(a.handleJsonResponse<AccountType[]>);
}

function findAccount(id: string): Promise<AccountType> {
  return $fetch(`/api/model/account/${id}`, a.authGet()).then(a.handleJsonResponse<AccountType>);
}

function createAccount(account: AccountType): Promise<AccountType> {
  return $fetch(`/api/model/account/${AccountTypeDef.id(account)}`, a.authPutJson(account)).then(
    a.handleJsonResponse<AccountType>,
  );
}

function updateAccount(account: AccountType): Promise<AccountType> {
  return $fetch(`/api/model/account/${AccountTypeDef.id(account)}`, a.authPostJson(account)).then(
    a.handleJsonResponse<AccountType>,
  );
}

function deleteAccount(id: string, purge?: boolean): Promise<MobilettoOrmObject | MobilettoOrmPurgeResults> {
  return $fetch(`/api/model/account/${id}/${purge ? `?purge=${purge}` : ""}`, a.authDelete()).then(
    a.handleJsonResponse<MobilettoOrmObject | MobilettoOrmPurgeResults>,
  );
}
