/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event, H3Error } from "h3";
import { MobilettoOrmSyncError } from "mobiletto-orm-typedef";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "profileJob.delete", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "profileJob.delete", async (event: H3Event, session, account) => {
      const profileJobRepo = profileJobRepository();
      if (profileJobRepo.initialize) await profileJobRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(profileJobRepo.typeDef.idFieldName());
      try {
        const profileJob_by_id = await profileJobRepo.safeFindById(id);
        if (profileJob_by_id) {

          return await profileJobRepo.remove(profileJob_by_id);
        }
      } catch (e) {
        if (e instanceof H3Error) throw e;
        if (e instanceof MobilettoOrmSyncError) {
          logger.warn(`profileJob.delete: sync error: ${e}`);
          throw conflict();
        }
        logger.error(`profileJob.delete: unexpected error: ${e}`);
        throw serverError();
      }
      throw notFound(id);
    });
  });
});
