/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "mediaProfile.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "mediaProfile.lookup", async (event: H3Event, session, account) => {
      const mediaProfileRepo = mediaProfileRepository();
      if (mediaProfileRepo.initialize) await mediaProfileRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(mediaProfileRepo.typeDef.idFieldName());
      const mediaProfile_by_id = await mediaProfileRepo.safeFindById(id);
      if (mediaProfile_by_id) return mediaProfile_by_id;
      throw notFound(id);
    });
  });
});
