/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { MobilettoOrmNotFoundError, MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { MediaProfileType, MediaProfileTypeDef } from "yuebing-model";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "mediaProfile.update", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "mediaProfile.update", async (event: H3Event, session, account) => {
      const mediaProfileRepo = mediaProfileRepository();
      if (mediaProfileRepo.initialize) await mediaProfileRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(mediaProfileRepo.typeDef.idFieldName());
      const obj: MediaProfileType = await readBody(event);
      if (!obj) {
        throw badRequest();
      }
      if (MediaProfileTypeDef.id(obj) !== id) {
        const errs: MobilettoOrmValidationErrors = {};
        errs[mediaProfileRepo.typeDef.idFieldName()] = ["mismatch"];
        throw validationError(errs);
      } else {

        return await mediaProfileRepo.update(obj);
      }
    });
  });
});
