/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { MobilettoOrmNotFoundError, MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { SourceScanType, SourceScanTypeDef } from "yuebing-model";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "sourceScan.update", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "sourceScan.update", async (event: H3Event, session, account) => {
      const sourceScanRepo = sourceScanRepository();
      if (sourceScanRepo.initialize) await sourceScanRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(sourceScanRepo.typeDef.idFieldName());
      const obj: SourceScanType = await readBody(event);
      if (!obj) {
        throw badRequest();
      }
      if (SourceScanTypeDef.id(obj) !== id) {
        const errs: MobilettoOrmValidationErrors = {};
        errs[sourceScanRepo.typeDef.idFieldName()] = ["mismatch"];
        throw validationError(errs);
      } else {

        return await sourceScanRepo.update(obj);
      }
    });
  });
});
