/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "sourceScan.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "sourceScan.lookup", async (event: H3Event, session, account) => {
      const sourceScanRepo = sourceScanRepository();
      const id =event?.context?.params?.id;
      if (!id) throw notFound(sourceScanRepo.typeDef.idFieldName());
      const sourceScan_by_id = await sourceScanRepo.safeFindById(id);
      if (sourceScan_by_id) return sourceScan_by_id;
      throw notFound(id);
    });
  });
});
