/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { SourceScanTypeDef } from "yuebing-model";
import { MobilettoOrmFindApiOpts } from "/storeHelper.ts";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "sourceScan.search", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "sourceScan.search", async (event: H3Event, session, account) => {
      const opts: MobilettoOrmFindApiOpts = (await readBody(event)) || {};
      if (typeof SourceScanTypeDef.apiConfig.search?.validate === "function") {
        const validated = await SourceScanTypeDef.apiConfig.search.validate(account, null, opts);
        if (validated === true || (typeof validated === "object" && Object.keys(validated).length === 0)) {
          // successfully validated
        } else if (typeof validated === "object" && Object.keys(validated).length > 0) {
          throw validationError(validated);
        } else {
          throw validationError({global: ["validation"]});
        }
      }
      const sourceScanRepo = sourceScanRepository();
      if (sourceScanRepo.initialize) await sourceScanRepo.initialize();
      if (opts.field && opts.value) {
        return await sourceScanRepo.safeFindBy(opts.field, opts.value, opts.opts || {});
      } else if (opts.textSearch && SourceScanTypeDef.textSearchFields.length > 0) {
        return await sourceScanRepo.find({ predicate: (obj) => SourceScanTypeDef.textMatch(obj, opts.textSearch || "") });
      } else {
        return await sourceScanRepo.find(opts.opts || {});
      }
    });
  });
});
