/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "mediaOperation.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "mediaOperation.lookup", async (event: H3Event, session, account) => {
      const mediaOperationRepo = mediaOperationRepository();
      const id =event?.context?.params?.id;
      if (!id) throw notFound(mediaOperationRepo.typeDef.idFieldName());
      const mediaOperation_by_id = await mediaOperationRepo.safeFindById(id);
      if (mediaOperation_by_id) return mediaOperation_by_id;
      throw notFound(id);
    });
  });
});
