/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { PrivateConfigType, PrivateConfigTypeDef } from "yuebing-model";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "privateConfig.update", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "privateConfig.update", async (event: H3Event, session, account) => {
      const privateConfigRepo = privateConfigRepository();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(privateConfigRepo.typeDef.idFieldName());
      const obj: PrivateConfigType = await readBody(event);
      if (!obj) {
        throw badRequest();
      }
      if (PrivateConfigTypeDef.id(obj) !== id) {
        const errs: MobilettoOrmValidationErrors = {};
        errs[privateConfigRepo.typeDef.idFieldName()] = ["mismatch"];
        throw validationError(errs);
      } else {

        return await privateConfigRepo.update(obj);
      }
    });
  });
});
