// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm";
import { DiscoveredAssetType, DiscoveredAssetTypeDef } from "yuebing-model";
import { discoveredAssetService } from "~/utils/services/model/discoveredAssetService";
import { MobilettoOrmFindApiOpts, updateOrmList } from "~/utils/model/storeHelper.js";

const updateList = (list: DiscoveredAssetType[] | null, id: string, opts?: { object?: DiscoveredAssetType; remove?: boolean }) => {
  return updateOrmList<DiscoveredAssetType>(DiscoveredAssetTypeDef, list, id, opts);
};

export const useDiscoveredAssetStore = defineStore("discoveredAsset", {
  state: () => ({
    finding: false,
    found: null as DiscoveredAssetType | null,
    creating: false,
    created: null as DiscoveredAssetType | null,
    updating: false,
    updated: null as DiscoveredAssetType | null,
    deleting: false,
    deleted: null as boolean | null,
    searching: false,
    discoveredAssetList: null as DiscoveredAssetType[] | null,
  }),
  getters: {
      discoveredAssetBusy: (state) => state.finding || state.creating || state.updating || state.deleting || state.searching,
  },
  actions: {
    async lookup(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<DiscoveredAssetType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await discoveredAssetService.findDiscoveredAsset(id, serverErrors);
        if (this.found) {
          updateList(this.discoveredAssetList, DiscoveredAssetTypeDef.id(this.found), {object: this.found});
        }
        return this.found;
      } finally {
        this.finding = false;
      }
    },
    async search(query?: MobilettoOrmFindApiOpts): Promise<DiscoveredAssetType[]> {
      try {
        this.searching = true;
        this.discoveredAssetList = await discoveredAssetService.searchDiscoveredAsset(query);
        return this.discoveredAssetList || [];
      } finally {
        this.searching = false;
      }
    },
    async create(object: DiscoveredAssetType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<DiscoveredAssetType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await discoveredAssetService.createDiscoveredAsset(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: DiscoveredAssetType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<DiscoveredAssetType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await discoveredAssetService.updateDiscoveredAsset(object, serverErrors);
        if (this.updated) {
          updateList(this.discoveredAssetList, DiscoveredAssetTypeDef.id(this.updated), {object: this.updated});
        }
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await discoveredAssetService.deleteDiscoveredAsset(id, serverErrors, !!purge);
        if (deleteResult) {
          updateList(this.discoveredAssetList, id, { remove: true });
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
