// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { DownloadedAssetType, DownloadedAssetTypeDef } from "yuebing-model";
import { downloadedAssetService } from "~/utils/services/model/downloadedAssetService";
import { MobilettoOrmFindApiOpts, updateOrmList } from "~/utils/model/storeHelper.js";

const updateList = (list: DownloadedAssetType[] | null, id: string, opts?: { object?: DownloadedAssetType; remove?: boolean }) => {
  return updateOrmList<DownloadedAssetType>(DownloadedAssetTypeDef, list, id, opts);
};

export const useDownloadedAssetStore = defineStore("downloadedAsset", {
  state: () => ({
    finding: false,
    found: null as DownloadedAssetType | null,
    creating: false,
    created: null as DownloadedAssetType | null,
    updating: false,
    updated: null as DownloadedAssetType | null,
    deleting: false,
    deleted: null as boolean | null,
    searching: false,
    downloadedAssetList: null as DownloadedAssetType[] | null,
  }),
  getters: {
      downloadedAssetBusy: (state) => state.finding || state.creating || state.updating || state.deleting || state.searching,
  },
  actions: {
    async lookup(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<DownloadedAssetType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await downloadedAssetService.findDownloadedAsset(id, serverErrors);
        if (this.found) {
          updateList(this.downloadedAssetList, DownloadedAssetTypeDef.id(this.found), {object: this.found});
        }
        return this.found;
      } finally {
        this.finding = false;
      }
    },
    async search(query?: MobilettoOrmFindApiOpts): Promise<DownloadedAssetType[]> {
      try {
        this.searching = true;
        this.downloadedAssetList = await downloadedAssetService.searchDownloadedAsset(query);
        return this.downloadedAssetList || [];
      } finally {
        this.searching = false;
      }
    },
    async create(object: DownloadedAssetType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<DownloadedAssetType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await downloadedAssetService.createDownloadedAsset(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: DownloadedAssetType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<DownloadedAssetType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await downloadedAssetService.updateDownloadedAsset(object, serverErrors);
        if (this.updated) {
          updateList(this.downloadedAssetList, DownloadedAssetTypeDef.id(this.updated), {object: this.updated});
        }
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await downloadedAssetService.deleteDownloadedAsset(id, serverErrors, !!purge);
        if (deleteResult) {
          updateList(this.downloadedAssetList, id, { remove: true });
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
