// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { LibraryScanType, LibraryScanTypeDef } from "yuebing-model";
import { libraryScanService } from "~/utils/services/model/libraryScanService";
import { MobilettoOrmFindApiOpts, updateOrmList } from "~/utils/model/storeHelper.js";

const updateList = (list: LibraryScanType[] | null, id: string, opts?: { object?: LibraryScanType; remove?: boolean }) => {
  return updateOrmList<LibraryScanType>(LibraryScanTypeDef, list, id, opts);
};

export const useLibraryScanStore = defineStore("libraryScan", {
  state: () => ({
    finding: false,
    found: null as LibraryScanType | null,
    creating: false,
    created: null as LibraryScanType | null,
    updating: false,
    updated: null as LibraryScanType | null,
    deleting: false,
    deleted: null as boolean | null,
    searching: false,
    libraryScanList: null as LibraryScanType[] | null,
  }),
  getters: {
      libraryScanBusy: (state) => state.finding || state.creating || state.updating || state.deleting || state.searching,
  },
  actions: {
    async lookup(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<LibraryScanType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await libraryScanService.findLibraryScan(id, serverErrors);
        if (this.found) {
          updateList(this.libraryScanList, LibraryScanTypeDef.id(this.found), {object: this.found});
        }
        return this.found;
      } finally {
        this.finding = false;
      }
    },
    async search(query?: MobilettoOrmFindApiOpts): Promise<LibraryScanType[]> {
      try {
        this.searching = true;
        this.libraryScanList = await libraryScanService.searchLibraryScan(query);
        return this.libraryScanList || [];
      } finally {
        this.searching = false;
      }
    },
    async create(object: LibraryScanType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<LibraryScanType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await libraryScanService.createLibraryScan(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: LibraryScanType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<LibraryScanType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await libraryScanService.updateLibraryScan(object, serverErrors);
        if (this.updated) {
          updateList(this.libraryScanList, LibraryScanTypeDef.id(this.updated), {object: this.updated});
        }
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await libraryScanService.deleteLibraryScan(id, serverErrors, !!purge);
        if (deleteResult) {
          updateList(this.libraryScanList, id, { remove: true });
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
