// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { MediaType, MediaTypeDef } from "yuebing-model";
import { mediaService } from "~/utils/services/model/mediaService";
import { MobilettoOrmFindApiOpts, updateOrmList } from "~/utils/model/storeHelper.js";

const updateList = (list: MediaType[] | null, id: string, opts?: { object?: MediaType; remove?: boolean }) => {
  return updateOrmList<MediaType>(MediaTypeDef, list, id, opts);
};

export const useMediaStore = defineStore("media", {
  state: () => ({
    finding: false,
    found: null as MediaType | null,
    creating: false,
    created: null as MediaType | null,
    updating: false,
    updated: null as MediaType | null,
    deleting: false,
    deleted: null as boolean | null,
    searching: false,
    mediaList: null as MediaType[] | null,
  }),
  getters: {
      mediaBusy: (state) => state.finding || state.creating || state.updating || state.deleting || state.searching,
  },
  actions: {
    async lookup(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<MediaType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await mediaService.findMedia(id, serverErrors);
        if (this.found) {
          updateList(this.mediaList, MediaTypeDef.id(this.found), {object: this.found});
        }
        return this.found;
      } finally {
        this.finding = false;
      }
    },
    async search(query?: MobilettoOrmFindApiOpts): Promise<MediaType[]> {
      try {
        this.searching = true;
        this.mediaList = await mediaService.searchMedia(query);
        return this.mediaList || [];
      } finally {
        this.searching = false;
      }
    },
    async create(object: MediaType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<MediaType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await mediaService.createMedia(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: MediaType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<MediaType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await mediaService.updateMedia(object, serverErrors);
        if (this.updated) {
          updateList(this.mediaList, MediaTypeDef.id(this.updated), {object: this.updated});
        }
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await mediaService.deleteMedia(id, serverErrors, !!purge);
        if (deleteResult) {
          updateList(this.mediaList, id, { remove: true });
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
