// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { MediaPropertyType, MediaPropertyTypeDef } from "yuebing-model";
import { mediaPropertyService } from "~/utils/services/model/mediaPropertyService";
import { MobilettoOrmFindApiOpts, updateOrmList } from "~/utils/model/storeHelper.js";

const updateList = (list: MediaPropertyType[] | null, id: string, opts?: { object?: MediaPropertyType; remove?: boolean }) => {
  return updateOrmList<MediaPropertyType>(MediaPropertyTypeDef, list, id, opts);
};

export const useMediaPropertyStore = defineStore("mediaProperty", {
  state: () => ({
    finding: false,
    found: null as MediaPropertyType | null,
    creating: false,
    created: null as MediaPropertyType | null,
    updating: false,
    updated: null as MediaPropertyType | null,
    deleting: false,
    deleted: null as boolean | null,
    searching: false,
    mediaPropertyList: null as MediaPropertyType[] | null,
  }),
  getters: {
      mediaPropertyBusy: (state) => state.finding || state.creating || state.updating || state.deleting || state.searching,
  },
  actions: {
    async lookup(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<MediaPropertyType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await mediaPropertyService.findMediaProperty(id, serverErrors);
        if (this.found) {
          updateList(this.mediaPropertyList, MediaPropertyTypeDef.id(this.found), {object: this.found});
        }
        return this.found;
      } finally {
        this.finding = false;
      }
    },
    async search(query?: MobilettoOrmFindApiOpts): Promise<MediaPropertyType[]> {
      try {
        this.searching = true;
        this.mediaPropertyList = await mediaPropertyService.searchMediaProperty(query);
        return this.mediaPropertyList || [];
      } finally {
        this.searching = false;
      }
    },
    async create(object: MediaPropertyType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<MediaPropertyType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await mediaPropertyService.createMediaProperty(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: MediaPropertyType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<MediaPropertyType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await mediaPropertyService.updateMediaProperty(object, serverErrors);
        if (this.updated) {
          updateList(this.mediaPropertyList, MediaPropertyTypeDef.id(this.updated), {object: this.updated});
        }
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await mediaPropertyService.deleteMediaProperty(id, serverErrors, !!purge);
        if (deleteResult) {
          updateList(this.mediaPropertyList, id, { remove: true });
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
