// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm";
import { PrivateConfigType } from "yuebing-model";
import { privateConfigService } from "~/utils/services/model/privateConfigService";

export const usePrivateConfigStore = defineStore("privateConfig", {
  state: () => ({
    finding: false,
    found: null as PrivateConfigType | null,
    creating: false,
    created: null as PrivateConfigType | null,
    updating: false,
    updated: null as PrivateConfigType | null,
    deleting: false,
    deleted: null as boolean | null,
  }),
  getters: {
      privateConfigBusy: (state) => state.finding || state.creating || state.updating || state.deleting,
  },
  actions: {
    async lookup(serverErrors?: Ref<MobilettoOrmValidationErrors>): Promise<PrivateConfigType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await privateConfigService.findPrivateConfig(serverErrors);
        return this.found
      } finally {
        this.finding = false;
      }
    },
    async search(): Promise<PrivateConfigType[]> {
      return [await this.lookup()];
    },
    async create(object: PrivateConfigType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<PrivateConfigType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await privateConfigService.createPrivateConfig(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: PrivateConfigType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<PrivateConfigType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await privateConfigService.updatePrivateConfig(object, serverErrors);
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await privateConfigService.deletePrivateConfig(serverErrors, !!purge);
        if (deleteResult) {
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
