// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { ProfileJobType, ProfileJobTypeDef } from "yuebing-model";
import { profileJobService } from "~/utils/services/model/profileJobService";
import { MobilettoOrmFindApiOpts, updateOrmList } from "~/utils/model/storeHelper.js";

const updateList = (list: ProfileJobType[] | null, id: string, opts?: { object?: ProfileJobType; remove?: boolean }) => {
  return updateOrmList<ProfileJobType>(ProfileJobTypeDef, list, id, opts);
};

export const useProfileJobStore = defineStore("profileJob", {
  state: () => ({
    finding: false,
    found: null as ProfileJobType | null,
    creating: false,
    created: null as ProfileJobType | null,
    updating: false,
    updated: null as ProfileJobType | null,
    deleting: false,
    deleted: null as boolean | null,
    searching: false,
    profileJobList: null as ProfileJobType[] | null,
  }),
  getters: {
      profileJobBusy: (state) => state.finding || state.creating || state.updating || state.deleting || state.searching,
  },
  actions: {
    async lookup(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<ProfileJobType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await profileJobService.findProfileJob(id, serverErrors);
        if (this.found) {
          updateList(this.profileJobList, ProfileJobTypeDef.id(this.found), {object: this.found});
        }
        return this.found;
      } finally {
        this.finding = false;
      }
    },
    async search(query?: MobilettoOrmFindApiOpts): Promise<ProfileJobType[]> {
      try {
        this.searching = true;
        this.profileJobList = await profileJobService.searchProfileJob(query);
        return this.profileJobList || [];
      } finally {
        this.searching = false;
      }
    },
    async create(object: ProfileJobType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<ProfileJobType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await profileJobService.createProfileJob(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: ProfileJobType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<ProfileJobType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await profileJobService.updateProfileJob(object, serverErrors);
        if (this.updated) {
          updateList(this.profileJobList, ProfileJobTypeDef.id(this.updated), {object: this.updated});
        }
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await profileJobService.deleteProfileJob(id, serverErrors, !!purge);
        if (deleteResult) {
          updateList(this.profileJobList, id, { remove: true });
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
