// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { Ref } from "vue";
import { defineStore } from "pinia";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { SourceScanType, SourceScanTypeDef } from "yuebing-model";
import { sourceScanService } from "~/utils/services/model/sourceScanService";
import { MobilettoOrmFindApiOpts, updateOrmList } from "~/utils/model/storeHelper.js";

const updateList = (list: SourceScanType[] | null, id: string, opts?: { object?: SourceScanType; remove?: boolean }) => {
  return updateOrmList<SourceScanType>(SourceScanTypeDef, list, id, opts);
};

export const useSourceScanStore = defineStore("sourceScan", {
  state: () => ({
    finding: false,
    found: null as SourceScanType | null,
    creating: false,
    created: null as SourceScanType | null,
    updating: false,
    updated: null as SourceScanType | null,
    deleting: false,
    deleted: null as boolean | null,
    searching: false,
    sourceScanList: null as SourceScanType[] | null,
  }),
  getters: {
      sourceScanBusy: (state) => state.finding || state.creating || state.updating || state.deleting || state.searching,
  },
  actions: {
    async lookup(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<SourceScanType> {
      this.found = null;
      this.finding = true;
      try {
        this.found = await sourceScanService.findSourceScan(id, serverErrors);
        if (this.found) {
          updateList(this.sourceScanList, SourceScanTypeDef.id(this.found), {object: this.found});
        }
        return this.found;
      } finally {
        this.finding = false;
      }
    },
    async search(query?: MobilettoOrmFindApiOpts): Promise<SourceScanType[]> {
      try {
        this.searching = true;
        this.sourceScanList = await sourceScanService.searchSourceScan(query);
        return this.sourceScanList || [];
      } finally {
        this.searching = false;
      }
    },
    async create(object: SourceScanType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<SourceScanType> {
      try {
        this.created = null;
        this.creating = true;
        this.created = await sourceScanService.createSourceScan(object, serverErrors);
        return this.created;
      } finally {
        this.creating = false;
      }
    },
    async update(object: SourceScanType, serverErrors: Ref<MobilettoOrmValidationErrors>): Promise<SourceScanType> {
      try {
        this.updated = null;
        this.updating = true;
        this.updated = await sourceScanService.updateSourceScan(object, serverErrors);
        if (this.updated) {
          updateList(this.sourceScanList, SourceScanTypeDef.id(this.updated), {object: this.updated});
        }
        return this.updated;
      } finally {
        this.updating = false;
      }
    },
    async delete(id: string, serverErrors: Ref<MobilettoOrmValidationErrors>, purge?: boolean): Promise<boolean> {
      try {
        this.deleted = null;
        this.deleting = true;
        const deleteResult = await sourceScanService.deleteSourceScan(id, serverErrors, !!purge);
        if (deleteResult) {
          updateList(this.sourceScanList, id, { remove: true });
          this.deleted = true;
        } else {
          this.deleted = false;
        }
        return this.deleted;
      } finally {
        this.deleting = false;
      }
    },
  },
});
