<!-- DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen -->

<template>
  <v-container>
    <v-row v-if="successSnackbar && successSnackbar.length > 0">
      <KitSnackbarSuccess :text="successSnackbar" />
    </v-row>
    <v-row v-else-if="errorSnackbar && errorSnackbar.length > 0">
      <KitSnackbarError :text="errorSnackbar" />
    </v-row>
    <v-row>
      <v-col>
        <h2>{{ adminTitle() }}</h2>
        <b v-if="messageExists('title_media_admin_details', messages)">
          {{ messages.title_media_admin_details }}
        </b>
      </v-col>
    </v-row>
    <v-row v-if="addingObject">
      <v-col>
        <OrmForm
          v-if="allRefsLoaded() && mediaTypeDef"
          form-name="add_media_form"
          :type-def="mediaTypeDef"
          :type-name-message="typeNameMessage"
          :thing="addObject"
          :fields="mediaTypeDefFields"
          :create="true"
          :read-only-object="() => false"
          :server-errors="createMediaServerErrors"
          :label-prefixes="labelPfx"
          :hint-suffixes="['_description']"
          @submitted="onAddSubmitted"
          @update="onAddUpdated"
          @cancel="onAddCancel"
        />
      </v-col>
    </v-row>
    <v-row v-else-if="Object.keys(editingObject).length > 0">
      <v-col>
        <OrmForm
          v-if="allRefsLoaded() && mediaTypeDef"
          form-name="edit_media_form"
          :type-def="mediaTypeDef"
          type-name-message="typeNameMessage"
          :thing="editingObject"
          :fields="mediaTypeDefFields"
          :create="false"
          :read-only-object="() => false"
          :server-errors="editMediaServerErrors"
          :label-prefixes="labelPfx"
          :hint-suffixes="['_description']"
          @submitted="onEditSubmitted"
          @update="onEditUpdated"
          @cancel="onEditCancel"
        />
      </v-col>
    </v-row>
    <v-row v-else-if="allRefsLoaded() && mediaTypeDef">
      <v-col>
        <v-container>
          <v-form @submit.prevent="searchObjects">
            <v-row v-if="(mediaList && mediaList.length > 0) || searched">
              <v-col>
                  <v-text-field
                    v-model="searchTerms"
                    :label="messages.label_search"
                    :disabled="mediaStore.mediaBusy"
                    type="text"
                    name="searchTerms"
                    class="form-control"
                    @keyup.enter="searchObjects"
                  />
              </v-col>
            </v-row>
            <v-row>
              <v-col>
                <v-btn class="btn btn-primary" :disabled="mediaStore.mediaBusy" @click.stop="searchObjects">
                  <Icon name="material-symbols:search" />
                </v-btn>
              </v-col>
            </v-row>
          </v-form>
          <v-row>
            <v-col>
              <table v-if="mediaList && mediaList.length > 0">
                <thead>
                <tr>
                  <th v-for="(tableField, tableFieldIndex) in tableFields" :key="tableFieldIndex">
                  {{ fieldMessages[tableField] }}
                  </th>
                  <th v-if="Object.keys(actionConfigs).length > 0">
                  <Icon name="material-symbols:target" />
                  </th>
                  <th></th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="(obj, objIndex) in mediaList" :key="objIndex">
                  <td v-for="(fieldName, fieldIndex) in tableFields" :key="fieldIndex">
                  <OrmFieldDisplay v-if="mediaTypeDef.fields[fieldName] || fieldName.startsWith('_meta')" :field="fieldName.startsWith('_meta') ? metaField(fieldName) : mediaTypeDef.fields[fieldName]" :value="deepGet(obj, fieldName)" />
                  </td>
                  <td v-if="Object.keys(actionConfigs).length > 0">
                  <div v-for="(action, actionIndex) in Object.keys(actionConfigs)" :key="actionIndex">
                  <NuxtLink
                    v-if="actionEnabled(obj, action)"
                    :to="{ path: `${actionConfig(action).path}/${deepGet(obj, mediaTypeDef.idField(obj) as string)}` }"
                    >
                      <v-btn>
                          {{ messages[actionConfig(action).message] }}
                        </v-btn>
                      </NuxtLink>
                    </div>
                  </td>
                  <td>
                    <v-btn v-if="canEdit(obj, mediaList)" :disabled="mediaStore.mediaBusy" @click.stop="showEditOrm(obj)">
                      <Icon name="material-symbols:edit" />
                    </v-btn>
                  </td>
                  <td>
                    <v-btn v-if="canDelete(obj, mediaList)" :disabled="mediaStore.mediaBusy" @click.stop="delObject(obj)">
                      <Icon name="material-symbols:delete" />
                    </v-btn>
                  </td>
                </tr>
                </tbody>
              </table>
            </v-col>
          </v-row>
          <v-row v-if="canAdd()">
            <v-col>
              <v-btn class="btn btn-primary" :disabled="mediaStore.mediaBusy" @click.stop="showAddOrm">
                <Icon name="material-symbols:add" />
              </v-btn>
            </v-col>
          </v-row>
        </v-container>
      </v-col>
    </v-row>
    <v-row v-else>
      <v-col>
        <Icon name="material-symbols:clock-outline" />
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
  import { ref, watch, Ref } from "vue";
  import { storeToRefs } from "pinia";
  import {
    MobilettoOrmFieldDefConfig,
    MobilettoOrmObject,
    MobilettoOrmTypeDef,
    MobilettoOrmValidationErrors,
    metaField
  } from "mobiletto-orm-typedef";
  import { MediaType, MediaTypeDef } from "yuebing-model";
  import { findMessage, messageExists, parseMessage, normalizeMsg } from "hokey-runtime";
  import { useSessionStore } from "~/stores/sessionStore";
  import { useMediaStore } from "~/stores/model/mediaStore";
  import { deepUpdate } from "~/utils/model/adminHelper";
  import { MobilettoOrmFindApiOpts } from "~/utils/model/storeHelper";
  const successSnackbar = ref("");
  const errorSnackbar = ref("");
  type ActionConfig = {
    path: string;
    message: string;
    when: (obj: MobilettoOrmObject) => boolean;
  };
  const props = withDefaults(
    defineProps<{
      labelPrefixes: string[];
      typeNameMessage: string;
      msgAddSuccess: string;
      msgAddError: string;
      msgEditSuccess: string;
      msgEditError: string;
      msgDeleteSuccess: string;
      msgDeleteError: string;
      actionConfigs: Record<string, ActionConfig>;
      canAdd: () => boolean;
      canEdit: (obj: MobilettoOrmObject, objList: MobilettoOrmObject[]) => boolean;
      canDelete: (obj: MobilettoOrmObject, objList: MobilettoOrmObject[]) => boolean;
      deleteConfirmationMessage: string;
      maxDeleteConfirmations: number;
    }>(),{
      labelPrefixes: () => ["label_", ""],
      typeNameMessage: () => "typename_media",
      msgAddSuccess: () => "admin_info_added",
      msgAddError: () => "admin_info_add_error",
      msgEditSuccess: () => "admin_info_edited",
      msgEditError: () => "admin_info_edit_error",
      msgDeleteSuccess: () => "admin_info_deleted",
      msgDeleteError: () => "admin_info_delete_error",
      actionConfigs: () => ({}),
      canAdd: () => true,
      canEdit: () => true,
      canDelete: () => true,
      maxDeleteConfirmations: () => 3,
    },
  );

  const emit = defineEmits<{
    added: [obj: MediaType];
    addCanceled: [];
    edited: [obj: MediaType];
    editCanceled: [obj: MediaType];
    deleted: [obj: MediaType];
  }>();

  const labelPfx: Ref<string[]> = ref(["admin_label_media_", "label_", ""]);
  if (props.labelPrefixes) {
    props.labelPrefixes.forEach((p: string) => {
      if (!labelPfx.value.includes(p)) labelPfx.value.unshift(p);
    });
  }

  const sessionStore = useSessionStore();
  const { localeMessages } = storeToRefs(sessionStore);
  const messages = localeMessages;

  const adminTitle = () => messageExists("admin_title_media_administration", messages.value)
    ? messages.value.admin_title_media_administration
    : parseMessage("admin_title_site_administration", messages.value, { title: findMessage(props.typeNameMessage, messages.value, [""])});

  const addingObject = ref(false);
  const addObject = ref({} as MediaType);
  const createMediaServerErrors = ref({} as MobilettoOrmValidationErrors);

  const editingObject = ref({} as MediaType);
  const editMediaServerErrors = ref({} as MobilettoOrmValidationErrors);
  const deleteMediaServerErrors = ref({} as MobilettoOrmValidationErrors);

  const pageNumber = ref(1);
  const pageSize = ref(20);
  const searchTerms = ref("");
  const searched = ref(false);
  const lastQuery = ref({});

  const tableFields: Ref<string[]> = ref([]);

  const fieldMessages: Ref<Record<string, string>> = ref({});
  const initFieldMessages = (tableFields: string[]) => {
      const defaultFieldMessages: Record<string, string> = {};
      tableFields.forEach((f: string) => {
        defaultFieldMessages[f] = findMessage(normalizeMsg(f), messages.value, props.labelPrefixes);
      });      fieldMessages.value = defaultFieldMessages;
  };

  const mediaStore = useMediaStore();
  const { mediaList  } = storeToRefs(mediaStore);
  const mediaTypeDef: Ref<MobilettoOrmTypeDef | null> = ref(null);
  const mediaTypeDefFields: Ref<MobilettoOrmFieldDefConfig[] | undefined> = ref(undefined);
  const searchQuery = () => {
      const q: MobilettoOrmFindApiOpts = {};
      if (searchTerms.value && searchTerms.value.trim().length > 0) q.textSearch = searchTerms.value;
            return Object.keys(q).length > 0 ? q : undefined;
  };

  const searchObjects = () => {
    const query = searchQuery();
    if (!query) return; // something was wrong, don't send the query
    if (lastQuery.value && JSON.stringify(lastQuery.value) === JSON.stringify(query)) {
      // not sending duplicate search
    } else {
      searched.value = true;
      lastQuery.value = Object.assign({}, query);
      mediaStore.search(query);
    }
  };

  const navigating = ref(false);

  const allRefsLoaded = () => true;
  mediaTypeDef.value = MediaTypeDef;
  mediaTypeDefFields.value = MediaTypeDef.tabIndexedFields();
  tableFields.value = mediaTypeDef.value.tableFields && Array.isArray(mediaTypeDef.value.tableFields)
    ? mediaTypeDef.value.tableFields
    : mediaTypeDef.value.primary
      ? [mediaTypeDef.value.primary, "ctime", "mtime"]
      : ["id", "ctime", "mtime"];
  initFieldMessages(tableFields.value);

  const onAddUpdated = (update: { field: string; value: any }) => {
    deepUpdate(addObject.value, update.field, update.value);
  };
  const onAddSubmitted = async (obj: MobilettoOrmObject) => {
    await mediaStore
      .create(obj as MediaType, createMediaServerErrors);
    addingObject.value = false;
    successSnackbar.value = parseMessage(props.msgAddSuccess, messages.value, {
        type: messages.value.typename_media,
        id: MediaTypeDef.id(obj),
    });
    emit("added", obj);
    addObject.value = {} as MediaType;
    return await mediaStore.search();
  }
  watch(createMediaServerErrors, () => {
    if (createMediaServerErrors.value && Object.keys(createMediaServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgAddError, messages.value, {
        type: messages.value.typename_media,
        error: JSON.stringify(createMediaServerErrors),
      });
    }
  });

  const showAddOrm = () => {
    addingObject.value = true;
  };
  const onAddCancel = () => {
    addingObject.value = false;
    emit("addCanceled");
  };

  const onEditUpdated = (update: { field: string; value: any }) => {
    if (editingObject.value) {
      deepUpdate(editingObject.value, update.field, update.value);
    }
  };

  const onEditSubmitted = async (obj: MobilettoOrmObject) => {
    await mediaStore
      .update(obj as MediaType, editMediaServerErrors);
    editingObject.value = {} as MediaType;
    successSnackbar.value = parseMessage(props.msgEditSuccess, messages.value, {
      type: messages.value.typename_media,
      id: MediaTypeDef.id(obj),
    });
    emit("edited", obj);
    return await mediaStore.search();
  };
  watch(editMediaServerErrors, () => {
    if (editMediaServerErrors.value && Object.keys(editMediaServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgEditError, messages.value, {
        type: messages.value.typename_media,
        id: MediaTypeDef.id(editingObject.value),
        error: JSON.stringify(editMediaServerErrors),
      });
    }
  });

  const showEditOrm = (obj: MobilettoOrmObject) => {
    if (Object.keys(editingObject.value).length > 0) {
      // already editing something else
      return;
    }
    if (obj) {
      const id = MediaTypeDef.id(obj);
      if (id && id.length > 0) {
        addingObject.value = false; // ensure add form is closed
        editingObject.value = JSON.parse(JSON.stringify(obj)) as MediaType;
      }
    }
  };
  const onEditCancel = () => {
    emit("editCanceled", editingObject.value);
    editingObject.value = {} as MediaType;
  };

  const actionConfig = (action: string) => {
    return props.actionConfigs[action];
  };

  const actionEnabled = (obj: MobilettoOrmObject, action: string) => {
    const cfg = props.actionConfigs[action];
    if (!cfg.when || typeof cfg.when !== "function") {
      return true;
    }
    if (typeof cfg.when === "function") {
      return cfg.when(obj) === true;
    }
    return true;
  };
  const delConfirmCount = ref(0);
  const deletingObject = ref(null);
  const delObject = (obj: MobilettoOrmObject) => {
      if (props.deleteConfirmationMessage && props.deleteConfirmationMessage.length > 0 && delConfirmCount.value < props.maxDeleteConfirmations) {
          const confirmationMessage = parseMessage(props.deleteConfirmationMessage, messages.value, {
              id: MediaTypeDef.id(obj)
          });
          if (confirm(confirmationMessage)) {
              delConfirmCount.value = delConfirmCount.value + 1;
          } else {
              delConfirmCount.value = 0;
              return;
          }
      }
      deletingObject.value = obj;
      const id = MediaTypeDef.id(obj);
      mediaStore.delete(id, deleteMediaServerErrors)
          .then(() => {
              successSnackbar.value = parseMessage(props.msgDeleteSuccess, messages.value, {
                  type: messages.value.typename_media,
                  id: MediaTypeDef.id(obj),
              });
              emit("deleted", obj);
              return mediaStore.search();
          });
  };
  watch(deleteMediaServerErrors, () => {
    if (deleteMediaServerErrors.value && Object.keys(deleteMediaServerErrors.value).length > 0) {
        errorSnackbar.value = parseMessage(props.msgDeleteError, messages.value, {
            type: messages.value.typename_media,
            id: deletingObject.value ? MediaTypeDef.id(deletingObject.value) : "null",
            error: JSON.stringify(deleteMediaServerErrors),
        });
    }
  });
  watch(mediaList, (newList) => {
    if (newList && Array.isArray(newList) && newList.length === 0 && searchTerms.value && searchTerms.value.length === 0) {
      if (navigating.value) return;
      navigating.value = true;
      navigateTo("/admin/media/setup");
    }
  });

  const initRefs = async () => {
    
  };
  mediaStore.search();
</script>
