/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { MobilettoOrmValidationErrors } from "mobiletto-orm-typedef";
import { LocalConfigType, LocalConfigTypeDef } from "yuebing-model";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "localConfig.create", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "localConfig.create", async (event: H3Event, session, account) => {
      const localConfigRepo = localConfigRepository();
      if (localConfigRepo.initialize) await localConfigRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(localConfigRepo.typeDef.idFieldName());
      const obj: LocalConfigType = await readBody(event);
      if (!obj) {
        throw badRequest();
      }
      if (LocalConfigTypeDef.id(obj) !== id) {
        const errs: MobilettoOrmValidationErrors = {};
        errs[localConfigRepo.typeDef.idFieldName()] = ["mismatch"];
        throw validationError(errs);
      } else {
        return await localConfigRepo.create(obj);
      }
    });
  });
});
