<!-- DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen -->

<template>
  <v-container>
    <v-row>
      <v-col>
        <h2>{{ adminTitle() }}</h2>
        <b v-if="messageExists('title_privateConfig_admin_details', messages)">
          {{ messages.title_privateConfig_admin_details }}
        </b>
      </v-col>
    </v-row>
    <div>
      <v-row v-if="addingObject">
        <v-col>
          <OrmForm
            v-if="allRefsLoaded() && privateConfigTypeDef"
            form-name="add_privateConfig_form"
            :type-def="privateConfigTypeDef"
            :type-name-message="typeNameMessage"
            :thing="addObject"
            :fields="privateConfigTypeDefFields"
            :create="true"
            :read-only-object="() => false"
            :server-errors="createPrivateConfigServerErrors"
            :label-prefixes="labelPfx"
            :hint-suffixes="['_description']"
            cancel-button-message=""
            @submitted="onAddSubmitted"
            @update="onAddUpdated"
          />
        </v-col>
      </v-row>
      <v-row v-else-if="Object.keys(editingObject).length > 0">
        <v-col>
          <OrmForm
            v-if="allRefsLoaded() && privateConfigTypeDef"
            form-name="edit_privateConfig_form"
            :type-def="privateConfigTypeDef"
            type-name-message="typeNameMessage"
            :thing="editingObject"
            :fields="privateConfigTypeDefFields"
            :create="false"
            :read-only-object="() => false"
            :server-errors="editPrivateConfigServerErrors"
            :label-prefixes="labelPfx"
            :hint-suffixes="['_description']"
            @submitted="onEditSubmitted"
            @update="onEditUpdated"
            @cancel="onEditCancel"
          />
        </v-col>
      </v-row>
      <v-row v-else>
        <v-col>
          <Icon name="material-symbols:clock-outline" />
        </v-col>
      </v-row>
    </div>
  </v-container>
</template>

<script setup lang="ts">
  import { ref, watch, Ref } from "vue";
  import { storeToRefs } from "pinia";
  import {
    MobilettoOrmFieldDefConfig,
    MobilettoOrmObject,
    MobilettoOrmTypeDef,
    MobilettoOrmValidationErrors,
    metaField
  } from "mobiletto-orm-typedef";
  import { PrivateConfigType, PrivateConfigTypeDef } from "yuebing-model";
  import { findMessage, messageExists, parseMessage } from "hokey-runtime";
  import { useSessionStore } from "~/stores/sessionStore";
  import { usePrivateConfigStore } from "~/stores/model/privateConfigStore";
  import { deepUpdate } from "~/utils/model/adminHelper";

  const props = withDefaults(
    defineProps<{
      labelPrefixes: string[];
      typeNameMessage: string,
    }>(),{
      labelPrefixes: () => ["label_", ""],
      typeNameMessage: () => "typename_privateConfig",
    },
  );

  const labelPfx: Ref<string[]> = ref(["admin_label_privateConfig_", "label_", ""]);
  if (props.labelPrefixes) {
    props.labelPrefixes.forEach((p: string) => {
      if (!labelPfx.value.includes(p)) labelPfx.value.unshift(p);
    });
  }

  const sessionStore = useSessionStore();
  const { localeMessages } = storeToRefs(sessionStore);
  const messages = localeMessages;

  const adminTitle = () => messageExists("admin_title_privateConfig_administration", messages.value)
    ? messages.value.admin_title_privateConfig_administration
    : parseMessage("admin_title_site_administration", messages.value, { title: findMessage(props.typeNameMessage, messages.value, [""])});

  const addingObject = ref(false);
  const addObject = ref({} as PrivateConfigType);
  const createPrivateConfigServerErrors = ref({} as MobilettoOrmValidationErrors);

  const editingObject = ref({} as PrivateConfigType);
  const editPrivateConfigServerErrors = ref({} as MobilettoOrmValidationErrors);

  const privateConfigStore = usePrivateConfigStore();
  const { found } = storeToRefs(privateConfigStore);
  
  const privateConfigTypeDef: Ref<MobilettoOrmTypeDef | null> = ref(null);
  const privateConfigTypeDefFields: Ref<MobilettoOrmFieldDefConfig[] | undefined> = ref(undefined);
  const findSingletonPrivateConfigServerErrors = ref({} as MobilettoOrmValidationErrors);


  const allRefsLoaded = () => true;
  privateConfigTypeDef.value = PrivateConfigTypeDef;
  privateConfigTypeDefFields.value = PrivateConfigTypeDef.tabIndexedFields();

  const onAddUpdated = (update: { field: string; value: any }) => {
    deepUpdate(addObject.value, update.field, update.value);
  };
  const onAddSubmitted = async (obj: MobilettoOrmObject) => {
    await privateConfigStore
      .create(obj as PrivateConfigType, createPrivateConfigServerErrors);
    addingObject.value = false;
    return await privateConfigStore.lookup(findSingletonPrivateConfigServerErrors);
  }

  const showAddOrm = () => {
    addingObject.value = true;
  };

  const onEditUpdated = (update: { field: string; value: any }) => {
    if (editingObject.value) {
      deepUpdate(editingObject.value, update.field, update.value);
    }
  };

  const onEditSubmitted = async (obj: MobilettoOrmObject) => {
    await privateConfigStore
      .update(obj as PrivateConfigType, editPrivateConfigServerErrors);
        editingObject.value = {} as PrivateConfigType;
        return await privateConfigStore.lookup(findSingletonPrivateConfigServerErrors);
  };

  const showEditOrm = (obj: MobilettoOrmObject) => {
    if (Object.keys(editingObject.value).length > 0) {
      // already editing something else
      return;
    }
    if (obj) {
      const id = PrivateConfigTypeDef.id(obj);
      if (id && id.length > 0) {
        editingObject.value = JSON.parse(JSON.stringify(obj)) as PrivateConfigType;
      }
    }
  };
  const onEditCancel = () => {
    editingObject.value = JSON.parse(JSON.stringify(found)) as PrivateConfigType;
  };
  watch(found, (newFound: MobilettoOrmObject) => {
    if (newFound && PrivateConfigTypeDef.id(newFound)) {
      showEditOrm(newFound)
    } else {
      showAddOrm();
    }
  });
  watch(findSingletonPrivateConfigServerErrors, (newErrors) => {
    console.log(`findSingleton errors: ${JSON.stringify(newErrors)}`);
  });
  privateConfigStore.lookup(findSingletonPrivateConfigServerErrors);
</script>
