<!-- DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen -->

<template>
  <v-container>
    <v-row v-if="successSnackbar && successSnackbar.length > 0">
      <KitSnackbarSuccess :text="successSnackbar" />
    </v-row>
    <v-row v-else-if="errorSnackbar && errorSnackbar.length > 0">
      <KitSnackbarError :text="errorSnackbar" />
    </v-row>
    <v-row>
      <v-col>
        <h2>{{ adminTitle() }}</h2>
        <b v-if="messageExists('admin_title_privateConfig_administration_details', messages)">
          {{ messages.admin_title_privateConfig_administration_details }}
        </b>
      </v-col>
    </v-row>
    <v-row v-if="addingObject">
      <v-col>
        <OrmForm
          v-if="allRefsLoaded() && privateConfigTypeDef"
          form-name="add_privateConfig_form"
          :type-def="privateConfigTypeDef"
          :type-name-message="typeNameMessage"
          :thing="addObject"
          :fields="privateConfigTypeDefFields"
          :create="true"
          :read-only-object="() => false"
          :server-errors="createPrivateConfigServerErrors"
          :label-prefixes="labelPfx"
          :hint-suffixes="['_description']"
          @submitted="onAddSubmitted"
          @update="onAddUpdated"
          @cancel="onAddCancel"
        />
      </v-col>
    </v-row>
    <v-row v-else-if="Object.keys(editingObject).length > 0">
      <v-col>
        <OrmForm
          v-if="allRefsLoaded() && privateConfigTypeDef"
          form-name="edit_privateConfig_form"
          :type-def="privateConfigTypeDef"
          type-name-message="typeNameMessage"
          :thing="editingObject"
          :fields="privateConfigTypeDefFields"
          :create="false"
          :read-only-object="() => false"
          :server-errors="editPrivateConfigServerErrors"
          :label-prefixes="labelPfx"
          :hint-suffixes="['_description']"
          @submitted="onEditSubmitted"
          @update="onEditUpdated"
          @cancel="onEditCancel"
        />
      </v-col>
    </v-row>
    <v-row v-else>
      <v-col>
        <Icon name="LoadingIcon" />
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
  import { ref, watch, Ref } from "vue";
  import { storeToRefs } from "pinia";
  import {
    MobilettoOrmFieldDefConfig,
    MobilettoOrmObject,
    MobilettoOrmTypeDef,
    MobilettoOrmValidationErrors,
    metaField
  } from "mobiletto-orm-typedef";
  import { PrivateConfigType, PrivateConfigTypeDef } from "yuebing-model";
  import { findMessage, messageExists, parseMessage } from "hokey-runtime";
  import { useSessionStore } from "~/stores/sessionStore";
  import { usePrivateConfigStore } from "~/stores/model/privateConfigStore";
  import { ActionConfig, deepUpdate } from "~/utils/model/adminHelper";
  import { MobilettoOrmFindApiOpts } from "~/utils/model/storeHelper";
  const successSnackbar = ref("");
  const errorSnackbar = ref("");
  const props = withDefaults(
    defineProps<{
      labelPrefixes: string[];
      typeNameMessage: string;
      msgAddSuccess: string;
      msgAddError: string;
      msgEditSuccess: string;
      msgEditError: string;
      msgFindSingletonError: string;
    }>(),{
      labelPrefixes: () => ["label_", ""],
      typeNameMessage: () => "typename_privateConfig",
      msgAddSuccess: () => "admin_info_added",
      msgAddError: () => "admin_info_add_error",
      msgEditSuccess: () => "admin_info_edited",
      msgEditError: () => "admin_info_edit_error",
      msgFindSingletonError: () => "admin_info_findSingleton_error",
    },
  );

  const emit = defineEmits<{
    added: [obj: MobilettoOrmObject];
    addCanceled: [];
    edited: [obj: MobilettoOrmObject];
    editCanceled: [obj: MobilettoOrmObject];
  }>();

  const labelPfx: Ref<string[]> = ref(["admin_label_privateConfig_", "label_", ""]);
  if (props.labelPrefixes) {
    props.labelPrefixes.forEach((p: string) => {
      if (!labelPfx.value.includes(p)) labelPfx.value.unshift(p);
    });
  }

  const sessionStore = useSessionStore();
  const { localeMessages } = storeToRefs(sessionStore);
  const messages = localeMessages;

  const adminTitle = () => messageExists("admin_title_privateConfig_administration", messages.value)
    ? messages.value.admin_title_privateConfig_administration
    : parseMessage("admin_title_site_administration", messages.value, { title: findMessage(props.typeNameMessage, messages.value, [""])});

  const addingObject = ref(false);
  const addObject = ref({} as PrivateConfigType);
  const createPrivateConfigServerErrors = ref({} as MobilettoOrmValidationErrors);

  const editingObject = ref({} as PrivateConfigType);
  const editPrivateConfigServerErrors = ref({} as MobilettoOrmValidationErrors);

  const privateConfigStore = usePrivateConfigStore();
  const { found } = storeToRefs(privateConfigStore);
  
  const privateConfigTypeDef: Ref<MobilettoOrmTypeDef | null> = ref(null);
  const privateConfigTypeDefFields: Ref<MobilettoOrmFieldDefConfig[] | undefined> = ref(undefined);
  const findSingletonPrivateConfigServerErrors = ref({} as MobilettoOrmValidationErrors);
  

  const allRefsLoaded = () => true;
  privateConfigTypeDef.value = PrivateConfigTypeDef;
  privateConfigTypeDefFields.value = PrivateConfigTypeDef.tabIndexedFields();

  const onAddUpdated = (update: { field: string; value: any }) => {
    deepUpdate(addObject.value, update.field, update.value);
  };
  const onAddSubmitted = async (obj: MobilettoOrmObject) => {
    await privateConfigStore
      .create(obj as PrivateConfigType, createPrivateConfigServerErrors);
    addingObject.value = false;
    successSnackbar.value = parseMessage(props.msgAddSuccess, messages.value, {
        type: messages.value.typename_privateConfig,
        id: PrivateConfigTypeDef.id(obj),
    });
    emit("added", obj);
    return await privateConfigStore.lookup(findSingletonPrivateConfigServerErrors);
  }
  watch(createPrivateConfigServerErrors, () => {
    if (createPrivateConfigServerErrors.value && Object.keys(createPrivateConfigServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgAddError, messages.value, {
        type: messages.value.typename_privateConfig,
        error: JSON.stringify(createPrivateConfigServerErrors),
      });
    }
  });

  const showAddOrm = () => {
    addingObject.value = true;
  };
  const onAddCancel = () => {
    addingObject.value = false;
    emit("addCanceled");
  };

  const onEditUpdated = (update: { field: string; value: any }) => {
    if (editingObject.value) {
      deepUpdate(editingObject.value, update.field, update.value);
    }
  };

  const onEditSubmitted = async (obj: MobilettoOrmObject) => {
    await privateConfigStore
      .update(obj as PrivateConfigType, editPrivateConfigServerErrors);
    
    successSnackbar.value = parseMessage(props.msgEditSuccess, messages.value, {
      type: messages.value.typename_privateConfig,
      id: PrivateConfigTypeDef.id(obj),
    });
    emit("edited", obj);
    return await privateConfigStore.lookup(findSingletonPrivateConfigServerErrors);
  };
  watch(editPrivateConfigServerErrors, () => {
    if (editPrivateConfigServerErrors.value && Object.keys(editPrivateConfigServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgEditError, messages.value, {
        type: messages.value.typename_privateConfig,
        id: PrivateConfigTypeDef.id(editingObject.value),
        error: JSON.stringify(editPrivateConfigServerErrors),
      });
    }
  });

  const showEditOrm = (obj: MobilettoOrmObject) => {
    if (Object.keys(editingObject.value).length > 0) {
      // already editing something else
      return;
    }
    if (obj) {
      const id = PrivateConfigTypeDef.id(obj);
      if (id && id.length > 0) {
        addingObject.value = false; // ensure add form is closed
        editingObject.value = JSON.parse(JSON.stringify(obj)) as PrivateConfigType;
      }
    }
  };
  const onEditCancel = () => {
    emit("editCanceled", editingObject.value);
    editingObject.value = JSON.parse(JSON.stringify(found.value)) as PrivateConfigType;
  };
  watch(found, () => {
    if (found.value && PrivateConfigTypeDef.id(found.value)) {
      showEditOrm(JSON.parse(JSON.stringify(found.value)));
    } else {
      showAddOrm();
    }
  });
  watch(findSingletonPrivateConfigServerErrors, () => {
    if (findSingletonPrivateConfigServerErrors.value && Object.keys(findSingletonPrivateConfigServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgFindSingletonError, messages.value, {
        type: messages.value.typename_privateConfig,
        error: JSON.stringify(findSingletonPrivateConfigServerErrors),
      });
    }
  });

  const initRefs = async () => {
    return await privateConfigStore.lookup(findSingletonPrivateConfigServerErrors);
  };
  initRefs()
      .then(obj => showEditOrm(obj))
      .catch(_e => showAddOrm());
</script>
