/* eslint-disable @typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";
import { LibraryScanTypeDef } from "yuebing-model";
import { MobilettoOrmFindApiOpts } from "/storeHelper.ts";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "libraryScan.search", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "libraryScan.search", async (event: H3Event, session, account) => {
      const opts: MobilettoOrmFindApiOpts = (await readBody(event)) || {};
      if (typeof LibraryScanTypeDef.apiConfig.search?.validate === "function") {
        const validated = await LibraryScanTypeDef.apiConfig.search.validate(account, null, opts);
        if (validated === true || (typeof validated === "object" && Object.keys(validated).length === 0)) {
          // successfully validated
        } else if (typeof validated === "object" && Object.keys(validated).length > 0) {
          throw validationError(validated);
        } else {
          throw validationError({global: ["validation"]});
        }
      }
      const libraryScanRepo = libraryScanRepository();
      if (libraryScanRepo.initialize) await libraryScanRepo.initialize();
      const predicate = opts.textSearch && opts.textSearch.trim().length > 0
        ? (obj) => LibraryScanTypeDef.textMatch(obj, opts.textSearch || "")
        : undefined;
      const requestedOpts = opts.opts || {};
      const searchOpts = predicate ? Object.assign({}, requestedOpts, { predicate }) : requestedOpts;
      if (opts.field && opts.value) {
        return await libraryScanRepo.safeFindBy(opts.field, opts.value, searchOpts);
      } else {
        return await libraryScanRepo.find(searchOpts);
      }
    });
  });
});
