/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "discoveredAsset.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "discoveredAsset.lookup", async (event: H3Event, session, account) => {
      const discoveredAssetRepo = discoveredAssetRepository();
      const id =event?.context?.params?.id;
      if (!id) throw notFound(discoveredAssetRepo.typeDef.idFieldName());
      const discoveredAsset_by_id = await discoveredAssetRepo.safeFindById(id);
      if (discoveredAsset_by_id) return discoveredAsset_by_id;
      throw notFound(id);
    });
  });
});
