/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event, H3Error } from "h3";
import { MobilettoOrmSyncError } from "mobiletto-orm-typedef";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "publicConfig.delete", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "publicConfig.delete", async (event: H3Event, session, account) => {
      const publicConfigRepo = publicConfigRepository();
      if (publicConfigRepo.initialize) await publicConfigRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(publicConfigRepo.typeDef.idFieldName());
      try {
        const publicConfig_by_id = await publicConfigRepo.safeFindById(id);
        if (publicConfig_by_id) {

          return await publicConfigRepo.remove(publicConfig_by_id);
        }
      } catch (e) {
        if (e instanceof H3Error) throw e;
        if (e instanceof MobilettoOrmSyncError) {
          logger.warn(`publicConfig.delete: sync error: ${e}`);
          throw conflict();
        }
        logger.error(`publicConfig.delete: unexpected error: ${e}`);
        throw serverError();
      }
      throw notFound(id);
    });
  });
});
