const VERIFY_EMAIL_PARAM = 'e'
const VERIFY_TOKEN_PARAM = 't'
const VERIFY_RESET_PARAM = 'r'
const VERIFY_PASSWORD_PARAM = 'p'
const VERIFY_ENDPOINT = '/verify'
const LOGIN_ENDPOINT = '/signIn'
const REGISTER_ENDPOINT = '/signUp'

module.exports = {
  VERIFY_ENDPOINT,
  VERIFY_EMAIL_PARAM,
  VERIFY_TOKEN_PARAM,
  VERIFY_RESET_PARAM,
  VERIFY_PASSWORD_PARAM,
  LOGIN_ENDPOINT,
  REGISTER_ENDPOINT
}
