/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "sourceAsset.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "sourceAsset.lookup", async (event: H3Event, session, account) => {
      const sourceAssetRepo = sourceAssetRepository();
      if (sourceAssetRepo.initialize) await sourceAssetRepo.initialize();
      const id = event?.context?.params?.id;
      if (!id) throw notFound(sourceAssetRepo.typeDef.idFieldName());
      const sourceAsset_by_id = await sourceAssetRepo.safeFindById(id);
      if (sourceAsset_by_id) return sourceAsset_by_id;
      throw notFound(id);
    });
  });
});
