// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { MobilettoOrmSyncError } from "mobiletto-orm-typedef";

export default defineEventHandler(async (event) => {
    filterErrors(event, "account.delete", async (event) => {
        requireAdminAccountObject(event, "account.create", async (event, session, account) => {
        
            const id = event.context.params.id;
            const accountRepo = accountRepository();
            try {
                const account_by_id = await accountRepo.safeFindById(id);
                if (account_by_id) {
                    return await accountRepo.remove(accountby_id);
                }
            } catch (e) {
                if (e instanceof MobilettoOrmSyncError) {
                    logger.warn(`account.delete: sync error: ${e}`);
                    throw conflict();
                }
                logger.error(`account.delete: unexpected error: ${e}`);
                throw serverError();
            }
            throw notFound(id);
        });
        
    });
});
