// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { AccountType, AccountTypeDef } from "yuebing-model";

export default defineEventHandler(async (event) => {
    filterErrors(event, "account.update", async (event) => {
        requireAdminAccountObject(event, "account.create", async (event, session, account) => {
        
            const id = event.context.params.id;
            const accountRepo = accountRepository();
            const obj: AccountType = await readBody(event);
            if (!obj) {
                throw createError({ statusCode: 400, statusMessage: "bad request" });
            }
            if (AccountTypeDef.id(obj) !== id) {
                throw createError({ statusCode: 422, statusMessage: "validation error", data: { id: ["mismatch"] } });
            } else {
                return await accountRepo.update(obj);
            }
        });
        
    });
});
