// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

export default defineEventHandler(async (event) => {
    filterErrors(event, "account.lookup", async (event) => {
        requireAdminAccountObject(event, "account.create", async (event, session, account) => {
        
            const id = event.context.params.id;
            const accountRepo = accountRepository();
            const account_by_id = await accountRepo.safeFindById(id);
            if (account_by_id) return account_by_id;
            const account_by_email = await accountRepo.safeFindFirstBy("email", id);
            if (account_by_email) return account_by_email;
            throw createError({statusCode: 404, statusMessage: "not found"});
        });
        
    });
});
