// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { MobilettoOrmFindOpts } from "mobiletto-orm";

export default defineEventHandler(async (event) => {
    filterErrors(event, "account.search", async (event) => {
        requireAdminAccountObject(event, "account.create", async (event, session, account) => {
        
            const accountRepo = accountRepository();
            const opts: MobilettoOrmFindApiOpts = await readBody(event) || {};
            if (opts.field && opts.value) {
                return await accountRepo.safeFindBy(opts.field, opts.value, opts.opts || {});
            } else {
                return await accountRepo.find(opts.opts || {});
            }
        });
        
    });
});
