/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "downloadedAsset.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "downloadedAsset.lookup", async (event: H3Event, session, account) => {
      const downloadedAssetRepo = downloadedAssetRepository();
      const id =event?.context?.params?.id;
      if (!id) throw notFound(downloadedAssetRepo.typeDef.idFieldName());
      const downloadedAsset_by_id = await downloadedAssetRepo.safeFindById(id);
      if (downloadedAsset_by_id) return downloadedAsset_by_id;
      throw notFound(id);
    });
  });
});
