/* eslint-disable camelcase,@typescript-eslint/no-unused-vars */
// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { H3Event } from "h3";

export default defineEventHandler(async (event: H3Event) => {
  return await filterErrors(event, "analyzedAsset.lookup", async (event: H3Event) => {
    return await requireAdminAccountObject(event, "analyzedAsset.lookup", async (event: H3Event, session, account) => {
      const analyzedAssetRepo = analyzedAssetRepository();
      const id =event?.context?.params?.id;
      if (!id) throw notFound(analyzedAssetRepo.typeDef.idFieldName());
      const analyzedAsset_by_id = await analyzedAssetRepo.safeFindById(id);
      if (analyzedAsset_by_id) return analyzedAsset_by_id;
      throw notFound(id);
    });
  });
});
