// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
// @eslint-disable camelcase

import { MobilettoOrmSyncError } from "mobiletto-orm-typedef";

export default defineEventHandler(async (event) => {
  filterErrors(event, "source.delete", async (event) => {
    requireAdminAccountObject(event, "source.delete", async (event, _session, _account) => {
      const id = event.context.params.id;
      const sourceRepo = sourceRepository();
      try {
        const source_by_id = await sourceRepo.safeFindById(id);
        if (source_by_id) {
          return await sourceRepo.remove(source_by_id);
        }
      } catch (e) {
        if (e instanceof MobilettoOrmSyncError) {
          logger.warn(`source.delete: sync error: ${e}`);
          throw conflict();
        }
        logger.error(`source.delete: unexpected error: ${e}`);
        throw serverError();
      }
      throw notFound(id);
    });
  });
});
