// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

import { SourceType, SourceTypeDef } from "yuebing-model";

export default defineEventHandler(async (event) => {
  filterErrors(event, "source.create", async (event) => {
    requireAdminAccountObject(event, "source.create", async (event, session, account) => {
      const id = event.context.params.id;
      const sourceRepo = sourceRepository();
      const obj: SourceType = await readBody(event);
      if (!obj) {
        throw createError({ statusCode: 400, statusMessage: "bad request" });
      }
      if (SourceTypeDef.id(obj) !== id) {
        throw createError({ statusCode: 422, statusMessage: "validation error", data: { id: ["mismatch"] } });
      } else {
        return await sourceRepo.create(obj);
      }
    });
  });
});
