// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen

export default defineEventHandler(async (event) => {
  filterErrors(event, "source.search", async (event) => {
    requireAdminAccountObject(event, "source.search", async (event, _session, _account) => {
      const sourceRepo = sourceRepository();
      const opts: MobilettoOrmFindApiOpts = (await readBody(event)) || {};
      if (opts.field && opts.value) {
        return await sourceRepo.safeFindBy(opts.field, opts.value, opts.opts || {});
      } else {
        return await sourceRepo.find(opts.opts || {});
      }
    });
  });
});
