<!-- DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen -->

<template>
  <v-container>
    <v-row v-if="successSnackbar && successSnackbar.length > 0">
      <KitSnackbarSuccess :text="successSnackbar" />
    </v-row>
    <v-row v-else-if="errorSnackbar && errorSnackbar.length > 0">
      <KitSnackbarError :text="errorSnackbar" />
    </v-row>
    <v-row>
      <v-col>
        <h2>{{ adminTitle() }}</h2>
        <b v-if="messageExists('title_publicConfig_admin_details', messages)">
          {{ messages.title_publicConfig_admin_details }}
        </b>
      </v-col>
    </v-row>
    <div>
      <v-row v-if="addingObject">
        <v-col>
          <OrmForm
            v-if="allRefsLoaded() && publicConfigTypeDef"
            form-name="add_publicConfig_form"
            :type-def="publicConfigTypeDef"
            :type-name-message="typeNameMessage"
            :thing="addObject"
            :fields="publicConfigTypeDefFields"
            :create="true"
            :read-only-object="() => false"
            :server-errors="createPublicConfigServerErrors"
            :label-prefixes="labelPfx"
            :hint-suffixes="['_description']"
            @submitted="onAddSubmitted"
            @update="onAddUpdated"
            @cancel="onAddCancel"
          />
        </v-col>
      </v-row>
      <v-row v-else-if="Object.keys(editingObject).length > 0">
        <v-col>
          <OrmForm
            v-if="allRefsLoaded() && publicConfigTypeDef"
            form-name="edit_publicConfig_form"
            :type-def="publicConfigTypeDef"
            type-name-message="typeNameMessage"
            :thing="editingObject"
            :fields="publicConfigTypeDefFields"
            :create="false"
            :read-only-object="() => false"
            :server-errors="editPublicConfigServerErrors"
            :label-prefixes="labelPfx"
            :hint-suffixes="['_description']"
            @submitted="onEditSubmitted"
            @update="onEditUpdated"
            @cancel="onEditCancel"
          />
        </v-col>
      </v-row>
      <v-row v-else>
        <v-col>
          <Icon name="material-symbols:clock-outline" />
        </v-col>
      </v-row>
    </div>
  </v-container>
</template>

<script setup lang="ts">
  import { ref, watch, Ref } from "vue";
  import { storeToRefs } from "pinia";
  import {
    MobilettoOrmFieldDefConfig,
    MobilettoOrmObject,
    MobilettoOrmTypeDef,
    MobilettoOrmValidationErrors,
    metaField
  } from "mobiletto-orm-typedef";
  import { PublicConfigType, PublicConfigTypeDef } from "yuebing-model";
  import { findMessage, messageExists, parseMessage } from "hokey-runtime";
  import { useSessionStore } from "~/stores/sessionStore";
  import { usePublicConfigStore } from "~/stores/model/publicConfigStore";
  import { deepUpdate } from "~/utils/model/adminHelper";
  const successSnackbar = ref("");
  const errorSnackbar = ref("");

  const props = withDefaults(
    defineProps<{
      labelPrefixes: string[];
      typeNameMessage: string;
      msgAddSuccess: string;
      msgAddError: string;
      msgEditSuccess: string;
      msgEditError: string;
      msgFindSingletonError: string;
    }>(),{
      labelPrefixes: () => ["label_", ""],
      typeNameMessage: () => "typename_publicConfig",
      msgAddSuccess: () => "admin_info_added",
      msgAddError: () => "admin_info_add_error",
      msgEditSuccess: () => "admin_info_edited",
      msgEditError: () => "admin_info_edit_error",
      msgFindSingletonError: () => "admin_info_findSingleton_error",
    },
  );

  const emit = defineEmits<{
    added: [obj: PublicConfigType];
    addCanceled: [];
    edited: [obj: PublicConfigType];
    editCanceled: [obj: PublicConfigType];
  }>();

  const labelPfx: Ref<string[]> = ref(["admin_label_publicConfig_", "label_", ""]);
  if (props.labelPrefixes) {
    props.labelPrefixes.forEach((p: string) => {
      if (!labelPfx.value.includes(p)) labelPfx.value.unshift(p);
    });
  }

  const sessionStore = useSessionStore();
  const { localeMessages } = storeToRefs(sessionStore);
  const messages = localeMessages;

  const adminTitle = () => messageExists("admin_title_publicConfig_administration", messages.value)
    ? messages.value.admin_title_publicConfig_administration
    : parseMessage("admin_title_site_administration", messages.value, { title: findMessage(props.typeNameMessage, messages.value, [""])});

  const addingObject = ref(false);
  const addObject = ref({} as PublicConfigType);
  const createPublicConfigServerErrors = ref({} as MobilettoOrmValidationErrors);

  const editingObject = ref({} as PublicConfigType);
  const editPublicConfigServerErrors = ref({} as MobilettoOrmValidationErrors);

  const publicConfigStore = usePublicConfigStore();
  const { found } = storeToRefs(publicConfigStore);
  
  const publicConfigTypeDef: Ref<MobilettoOrmTypeDef | null> = ref(null);
  const publicConfigTypeDefFields: Ref<MobilettoOrmFieldDefConfig[] | undefined> = ref(undefined);
  const findSingletonPublicConfigServerErrors = ref({} as MobilettoOrmValidationErrors);
  

  const allRefsLoaded = () => true;
  publicConfigTypeDef.value = PublicConfigTypeDef;
  publicConfigTypeDefFields.value = PublicConfigTypeDef.tabIndexedFields();

  const onAddUpdated = (update: { field: string; value: any }) => {
    deepUpdate(addObject.value, update.field, update.value);
  };
  const onAddSubmitted = async (obj: MobilettoOrmObject) => {
    await publicConfigStore
      .create(obj as PublicConfigType, createPublicConfigServerErrors);
    addingObject.value = false;
    successSnackbar.value = parseMessage(props.msgAddSuccess, messages.value, {
        type: messages.value.typename_publicConfig,
        id: PublicConfigTypeDef.id(obj),
    });
    emit("added", obj);
    return await publicConfigStore.lookup(findSingletonPublicConfigServerErrors);
  }
  watch(createPublicConfigServerErrors, () => {
    if (createPublicConfigServerErrors.value && Object.keys(createPublicConfigServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgAddError, messages.value, {
        type: messages.value.typename_publicConfig,
        error: JSON.stringify(createPublicConfigServerErrors),
      });
    }
  });

  const showAddOrm = () => {
    addingObject.value = true;
  };
  const onAddCancel = () => {
    addingObject.value = false;
    emit("addCanceled");
  };

  const onEditUpdated = (update: { field: string; value: any }) => {
    if (editingObject.value) {
      deepUpdate(editingObject.value, update.field, update.value);
    }
  };

  const onEditSubmitted = async (obj: MobilettoOrmObject) => {
    await publicConfigStore
      .update(obj as PublicConfigType, editPublicConfigServerErrors);
    
    successSnackbar.value = parseMessage(props.msgEditSuccess, messages.value, {
      type: messages.value.typename_publicConfig,
      id: PublicConfigTypeDef.id(obj),
    });
    emit("edited", obj);
    return await publicConfigStore.lookup(findSingletonPublicConfigServerErrors);
  };
  watch(editPublicConfigServerErrors, () => {
    if (editPublicConfigServerErrors.value && Object.keys(editPublicConfigServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgEditError, messages.value, {
        type: messages.value.typename_publicConfig,
        id: PublicConfigTypeDef.id(editingObject.value),
        error: JSON.stringify(editPublicConfigServerErrors),
      });
    }
  });

  const showEditOrm = (obj: MobilettoOrmObject) => {
    if (Object.keys(editingObject.value).length > 0) {
      // already editing something else
      return;
    }
    if (obj) {
      const id = PublicConfigTypeDef.id(obj);
      if (id && id.length > 0) {
        addingObject.value = false; // ensure add form is closed
        editingObject.value = JSON.parse(JSON.stringify(obj)) as PublicConfigType;
      }
    }
  };
  const onEditCancel = () => {
    emit("editCanceled", editingObject.value);
    editingObject.value = JSON.parse(JSON.stringify(found.value)) as PublicConfigType;
  };
  watch(found, () => {
    if (found.value && PublicConfigTypeDef.id(found.value)) {
      showEditOrm(JSON.parse(JSON.stringify(found.value)));
    } else {
      showAddOrm();
    }
  });
  watch(findSingletonPublicConfigServerErrors, () => {
    if (findSingletonPublicConfigServerErrors.value && Object.keys(findSingletonPublicConfigServerErrors.value).length > 0) {
      errorSnackbar.value = parseMessage(props.msgFindSingletonError, messages.value, {
        type: messages.value.typename_publicConfig,
        error: JSON.stringify(findSingletonPublicConfigServerErrors),
      });
    }
  });

  const initRefs = async () => {
    return await publicConfigStore.lookup(findSingletonPublicConfigServerErrors);
  };
  initRefs()
      .then(obj => showEditOrm(obj))
      .catch(_e => showAddOrm());
</script>
